### ISSUE TITLE
Sliders shrink as strings expand

### ISSUE THREAD

**Issue by arouinfar** [phetsims/hookes-law#29]
When testing for potential i18n issues, I noticed that the panels below the springs become <i>thinner</i> as the panel expands to accommodate longer strings. As a result the sliders shrink and can become quite small. At double string length, it's still usable in mouse environments, but it is quite difficult to use the sliders on an iPad. Ideally, the sliders/tweakers should stay the same size as the panels become wider. 

Regular panel size:
![image](https://cloud.githubusercontent.com/assets/8419308/10377371/26104876-6dc0-11e5-8a57-fdb92f123564.png)

?stringTest=double:
![image](https://cloud.githubusercontent.com/assets/8419308/10377366/1bf2a94c-6dc0-11e5-9811-140b1a5cdd1b.png)

A ridiculously long string:
![image](https://cloud.githubusercontent.com/assets/8419308/10377488/c7a85e8a-6dc0-11e5-83fc-8b9572584336.png)

**Comment by pixelzoom** [comment]
Our general approach has been to shrink the entire panel (rather than individual items in a panel) when a panel exceeds some maximum width.  And changing that behavior is problematic in this case, because the things in the panel are a common-code UI component (`NumberControl`) that provides no access to the label.  Providing direct access to the label will break encapsulation, so the preferred solution is to add an option to `NumberControl` that limits the width of its label.

**Comment by pixelzoom** [comment]
I'll also need to add an option to `NumberControl` to limit the width of the value field.

**Comment by pixelzoom** [comment]
Mentioning @ariel-phet here too.

I think that we should do this.  But since this involves changing common code (`NumberControl`), this will require pulling in 'master' version of all common-code repos, and a full RC test cycle.

**Comment by pixelzoom** [comment]
Since a full RC test cycle will likely be required to pull in the fix for https://github.com/phetsims/beers-law-lab/issues/112, I think we should just go for it.

**Comment by pixelzoom** [comment]
Changed in master and 1.0 branches. 

The change to `NumberControl` is in master, so we'll need to move to master for all common-code repos in the next RC version.

Since this was a fairly major change, I'm publishing dev version 1.1.0-dev.1 for testing.

@arouinfar could you please test the following:

Normal strings:
http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.1.0-dev.1/hookes-law_en.html?dev

Double strings:
http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.1.0-dev.1/hookes-law_en.html?dev&stringTest=double

Long strings:
http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.1.0-dev.1/hookes-law_en.html?dev&stringTest=long

Each of these runs with the "dev" query parameter, which will selects all check boxes, so that you can see all UI elements that have associated strings.

**Comment by ariel-phet** [comment]
Yep, comfortable with another RC. I think 2 RC's is very reasonable for a brand new sim!

**Comment by arouinfar** [comment]
I think the latest dev is looking pretty good @pixelzoom. The number readouts can at times feel a bit small, but realistically these strings are not going to need to grow by much (if at all). 

Should this issue remain open until the next round of RC testing or can it be closed now?

**Comment by pixelzoom** [comment]
Note that the fix herein caused #30, which is now fixed, but was present in 1.1.0-dev.1.

I'd like to leave this issue open, to remind me to pick up master of all repositories when I publish 1.0.0-rc.2.  I'll close it after that.

**Comment by pixelzoom** [comment]
> I'd like to leave this issue open, to remind me ...

Since I need to pick up master for other critical fixes, I don't need this reminder.

Closing.
