### ISSUE TITLE
overlap of Series springs on Systems screen

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/hookes-law#30]
Test device: iPad 2

Operating System: iOS 8.3

Browser: safari 

Problem description: Items on the screen are overlapping when there are two springs connected.

Steps to reproduce: Open Systems screen, select the connected springs. 

Severity:

Screenshots: 
![image](https://cloud.githubusercontent.com/assets/12610678/10433544/064edc24-70d0-11e5-913b-7e71fea2713e.jpg)

Troubleshooting information (do not edit):
Name: ‪Hooke's Law‬
URL: http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.1.0-dev.1/hookes-law_en.html
Version: 1.1.0-dev.1 2015-10-08 22:34:41 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F69 Safari/600.1.4
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-115.5)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"11bc6a6d","branch":"master"},"axon":{"sha":"47eaa1de","branch":"master"},"babel":{"sha":"931afbf1","branch":"master"},"brand":{"sha":"8a756e53","branch":"master"},"chipper":{"sha":"d93dfe7e","branch":"master"},"dot":{"sha":"09f891ac","branch":"master"},"hookes-law":{"sha":"12cede3b","branch":"master"},"joist":{"sha":"3fbd99f9","branch":"master"},"kite":{"sha":"81ce58ca","branch":"master"},"phet-core":{"sha":"f6348fba","branch":"master"},"phetcommon":{"sha":"0e4754fe","branch":"master"},"scenery":{"sha":"80935892","branch":"master"},"scenery-phet":{"sha":"34b1186d","branch":"master"},"sherpa":{"sha":"1759eade","branch":"master"},"sun":{"sha":"b66398a5","branch":"master"}}

**Comment by elisemorgan** [comment]
Also observed on Chromebook

**Comment by pixelzoom** [comment]
Not specific to iPad, I see this on desktop platforms. It's specific to the series-springs scene. 

For example, OS X + Safari:

![screenshot_33](https://cloud.githubusercontent.com/assets/3046552/10436884/9a01630e-70e6-11e5-853d-ab778c1efb92.png)

**Comment by pixelzoom** [comment]
This problem was introduced in the fix for #29.  And I just noticed that @elisemorgan is testing 1.1.0-dev.1, not the release candidate 1.0.0-rc.1.   And that's great, because this would have popped up in 1.0.0-rc.2.

I've fixed this over in #29 by restoring the scaling of complete panels if they exceed the space limitations. And that scaling occurs only for the series-spring scene.

Here's how it looks after the fix. Layout out is fine, and the fonts and sliders are smaller for the series-spring scene, as they were previously.

![screenshot_34](https://cloud.githubusercontent.com/assets/3046552/10437437/4f2ae888-70ea-11e5-871b-06e1ee345fc9.png)

Closing.
