### ISSUE TITLE
Scene controls can go out of bounds if visibility control is narrow

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/hookes-law#4]
Intro and systems scene controls can get pushed out of bounds if strings in the visibility control are short enough. Here are some captures of the effect:

In the Intro screen:

![introboundstest](https://cloud.githubusercontent.com/assets/6396244/8529695/702977ba-23d9-11e5-93d1-1d18908f86b9.PNG)

In the Systems screen:

![systemsboundstest](https://cloud.githubusercontent.com/assets/6396244/8529713/979948fc-23d9-11e5-9329-86ebaf4f7866.PNG)

It is unlikely that the visibility control will ever be this narrow, but it seemed worth mentioning.

**Comment by pixelzoom** [comment]
Good catch!  I've been checking i18n with long strings, but not short strings. The code-review checklist should be amended to include testing with short strings.  And this should be an easy fix in the sim.

**Comment by pixelzoom** [comment]
I added this step to the code-review checklist at https://github.com/phetsims/phet-info/blob/master/code_review_checklist.md

> - [ ] Does the sim layout gracefully handle internationalized strings that are shorter than the English strings? (run with query parameter 'stringTest=X')

**Comment by pixelzoom** [comment]
Fixed by putting a VBox around the visibility and scene controls.  Screenshots below show layout in the "Intro" screen for English, short and long strings.  The "Systems" screen was fixed similarly. Assigning back to @jessegreenberg to review.

![screenshot_556](https://cloud.githubusercontent.com/assets/3046552/8531914/daccbe34-23e7-11e5-9c18-f115317bf315.png)
![screenshot_555](https://cloud.githubusercontent.com/assets/3046552/8531915/dda2a1fa-23e7-11e5-9ffc-9ead4f54c362.png)
![screenshot_554](https://cloud.githubusercontent.com/assets/3046552/8531920/e0798d58-23e7-11e5-8211-ceae0ae13358.png)

**Comment by jessegreenberg** [comment]
Looking great!  Closing.
