### ISSUE TITLE
drag listeners aren't interrupted

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/hookes-law#92]
**Test device**
iPad 9th generation

**Operating System**
iPadOS 17.5.1

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/1102, since this is an older sim, I'm seeing the usual issue with the drag listeners on the iPad. 

**Steps to reproduce**
Ex. 
1. On any screen, move a slider thumb and hold it while pressing Reset All
2. Grab the handle and hold it while pressing Reset All

**Visuals**
I don't think a visual is need here :)

**Comment by pixelzoom** [comment]
Sure would be nice if ResetAllButton handled this. But I've suggested that before and it hasn't gotten any traction.  So fixed in https://github.com/phetsims/hookes-law/commit/6d066c0b018ba960ae7068c3df19a7786dddb6ba. (I also went through all of the sims that I'm responsible for, and preoactively addressed this in other older sims.)

@Nancy-Salpepi please verify, close if OK.

**Comment by Nancy-Salpepi** [comment]
Looks good on main.
Closing.
